name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    #- cron: "0 0 * * *" 
    - cron: "0,30 * * * *"
jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses:  Vivek-Murali/waka-readme@main
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: ->
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          SHOW_OS: true
          SHOW_PROJECTS: true
          SHOW_COMMITS: true
          SHOW_DAYS_OF_WEEK: "FALSE"
          SHOW_TIMEZONE: true
          SHOW_SHORT_INFO: true
